name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: mvn -B test
      - name: Publish package
        run: mvn -P prod -B package -DskipTests
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://oss.sonatype.org
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.github.akovari artifactId=antlr4-autocomplete version=0.0.1-SNAPSHOT
          assets: extension=jar
          filename: ./target/antlr4-autocomplete-0.0.1-SNAPSHOT.jar
